name: vehicle_rental_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

  cupertino_icons: ^1.0.8
  skeletonizer: ^2.0.1
  lottie: ^2.7.0
  http: ^1.4.0
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/logo.png
    - assets/images/cars/sedan.png
    - assets/images/cars/suv.png
    - assets/images/cars/hatchback.png
    - assets/images/bikes/sportsbike.png
    - assets/images/bikes/cruiser.png
    - assets/images/trucks/pickup.png
    - assets/images/trucks/lorry.png
    - assets/images/buses/minibus.png
    - assets/images/buses/coach.png
    - assets/images/vans/cargo.png
    - assets/images/vans/minivan.png
    - assets/animations/booking_completed_animation.json

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
